export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const SIGN_IN_WAITLIST_USER = 'SIGN_IN_WAITLIST_USER';
export const SIGN_UP_WAITLIST_USER = 'SIGN_UP_WAITLIST_USER';
export const SIGN_OUT_WAITLIST_USER = 'SIGN_OUT_WAITLIST_USER';
export const ADD_STAFF_TO_WAITLIST = 'ADD_STAFF_TO_WAITLIST';
export const ADD_SERVICE1_TO_WAITLIST = 'ADD_SERVICE1_TO_WAITLIST';
export const ADD_SERVICE2_TO_WAITLIST = 'ADD_SERVICE2_TO_WAITLIST';
export const SET_WAITLIST_VIEW = 'SET_WAITLIST_VIEW';
export const RESET_WAITLIST = 'RESET_WAITLIST';
export const REFRESH_TRUE = 'REFRESH_TRUE';
export const REFRESH_FALSE = 'REFRESH_FALSE';

