export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_UP_USER = 'SIGN_UP_USER';
export const ADD_STAFF_TO_WAITLIST = 'ADD_STAFF_TO_WAITLIST';
export const ADD_SERVICE_TO_WAITLIST = 'ADD_SERVICE_TO_WAITLIST';
export const SET_WAITLIST_VIEW = 'SET_WAITLIST_VIEW';

